version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: cmsuser
      WORDPRESS_DB_PASSWORD: xZzK2jok
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - type: bind
        source: /opt/docker/wp_data
        target: /var/www/html

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: xZzK2jok
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: /opt/docker/mysql_data
        target: /var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/docker/prometheus_config
        target: /etc/prometheus
      - type: bind
        source: /opt/docker/prometheus_data
        target: /prometheus
