version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: cmsuser
      WORDPRESS_DB_PASSWORD: xZzK2jok
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - type: bind
        source: /opt/docker/wp_data
        target: /var/www/html

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: cmsuser
      MYSQL_PASSWORD: xZzK2jok
      MYSQL_ROOT_PASSWORD: PwmkQ2cG
    volumes:
      - type: bind
        source: /opt/docker/mysql_data
        target: /var/lib/mysql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/docker/prometheus_config
        target: /etc/prometheus
      - type: bind
        source: /opt/docker/prometheus_data
        target: /prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - type: bind
        source: /opt/docker/grafana_data
        target: /etc/grafana/provisioning/datasources

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - 9115:9115
    restart: unless-stopped
    volumes: 
      - type: bind
        source: /opt/docker/exporters/blackbox
        target: /config

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld_exporter
    command:
      - '--config.my-cnf=/config/mysql.cnf'
    ports:
      - 9104:9104
    restart: unless-stopped
    volumes: 
      - type: bind
        source: /opt/docker/exporters/mysqld
        target: /config