global:
  scrape_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.50.11:9090

- job_name: blackbox
  metrics_path: /metrics
  static_configs:
    - targets:
      - 192.168.50.11:9115

- job_name: blackbox-http
  metrics_path: /probe
  params:
    module: [http_2xx]
    target: [192.168.50.11:8080] # Wordpress instance
  static_configs:
    - targets:
      - 192.168.50.11:9115