global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
      - 192.168.50.11:9090

- job_name: docker
  metrics_path: /metrics
  static_configs:
    - targets:
      - 192.168.50.11:9323

- job_name: blackbox
  metrics_path: /metrics
  static_configs:
    - targets:
      - 192.168.50.11:9115

- job_name: blackbox-http
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://192.168.50.11:8080
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.50.11:9115

- job_name: mysql
  params:
    auth_module: [client]
  static_configs:
    - targets:
      - 192.168.50.11:3306
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.50.11:9104