---
- name: Server init
  hosts: all
  become: true
  roles:
    - role: docker_install
      tags: init

- name: Containers deploy
  hosts: all
  roles:
    - role: cms_install
      tags: deploy

- name: Containers configuration
  hosts: all
  roles:
    - role: cms_config
      tags: config
