- name: Docker install
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: "present"
    update_cache: true

- name: Add to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    group: "docker"

- name: Create docker dir
  ansible.builtin.file:
    path: /opt/docker
    state: directory
    mode: '0755'
