- name: Create Wordpress directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /opt/docker/wp_data

- name: Create MySQL directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  loop:
    - /opt/docker/mysql_data

- name: Create Prometheus directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  loop:
    - /opt/docker/prometheus_config
    - /opt/docker/prometheus_data

- name: Create Alertmanager directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  loop:
    - /opt/docker/alertmanager_config
    - /opt/docker/alertmanager_data

- name: Create Grafana data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: nogroup
    mode: 0770
  loop:
    - /opt/docker/grafana_data

- name: Create exporters tree structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/docker/exporters
    - /opt/docker/exporters/blackbox
    - /opt/docker/exporters/mysqld

- name: Put Prometheus config to volume
  ansible.builtin.copy:
    src: ./files/prometheus.yml
    dest: /opt/docker/prometheus_config/prometheus.yml
    owner: root
    group: nogroup
    mode: 0640

- name: Put Prometheus alerts config to volume
  ansible.builtin.copy:
    src: ./files/alert.rules.yml
    dest: /opt/docker/prometheus_config/alert.rules.yml
    owner: root
    group: nogroup
    mode: 0640

- name: Put Alertmanager config to volume
  ansible.builtin.copy:
    src: ./files/alertmanager.yml
    dest: /opt/docker/alertmanager_config/alertmanager.yml
    owner: root
    group: nogroup
    mode: 0640

- name: Put blackbox-exporter config to volume
  ansible.builtin.copy:
    src: ./files/blackbox.yml
    dest: /opt/docker/exporters/blackbox/blackbox.yml
    owner: root
    group: nogroup
    mode: 0640

- name: Put mysql-exporter config to volume
  ansible.builtin.copy:
    src: ./files/mysql.cnf
    dest: /opt/docker/exporters/mysqld/mysql.cnf
    owner: root
    group: nogroup
    mode: 0640

- name: Put docker-compose to volume
  ansible.builtin.copy:
    src: ./files/docker-compose.yml
    dest: /opt/docker/docker-compose.yml
    owner: root
    group: root
    mode: 0600

- name: Deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /opt/docker
    files:
      - docker-compose.yml

- name: Pause for 15 seconds to running all containers
  ansible.builtin.pause:
    seconds: 15
