- name: Create Wordpress data directory
  become: true
  ansible.builtin.file:
    path: /opt/docker/wp_data
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create MySQL data directory
  become: true
  ansible.builtin.file:
    path: /opt/docker/mysql_data
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Create Prometheus config directory
  become: true
  ansible.builtin.file:
    path: /opt/docker/prometheus_config
    state: directory
    owner: root
    group: nogroup
    mode: 0750

- name: Create Prometheus data directory
  become: true
  ansible.builtin.file:
    path: /opt/docker/prometheus_data
    state: directory
    owner: root
    group: nogroup
    mode: 0770

- name: Create Grafana data directory
  become: true
  ansible.builtin.file:
    path: /opt/docker/grafana_data
    state: directory
    owner: root
    group: nogroup
    mode: 0770

- name: Create exporters tree structure
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/docker/exporters
    - /opt/docker/exporters/blackbox
    - /opt/docker/exporters/mysqld

- name: Put Prometheus config to volume
  become: true
  ansible.builtin.copy:
    src: ./files/prometheus.yml
    dest: /opt/docker/prometheus_config/prometheus.yml
    owner: root
    group: nogroup
    mode: 0640

- name: Put blackbox-exporter config to volume
  become: true
  ansible.builtin.copy:
    src: ./files/blackbox.yml
    dest: /opt/docker/exporters/blackbox/blackbox.yml
    owner: root
    group: nogroup
    mode: 0640

- name: Put mysql-exporter config to volume
  become: true
  ansible.builtin.copy:
    src: ./files/mysql.cnf
    dest: /opt/docker/exporters/mysqld/mysql.cnf
    owner: root
    group: nogroup
    mode: 0640

- name: Put docker-compose to volume
  become: true
  ansible.builtin.copy:
    src: ./files/docker-compose.yml
    dest: /opt/docker/docker-compose.yml
    owner: root
    group: root
    mode: 0600

- name: Deploy Docker Compose stack
  become: true
  community.docker.docker_compose:
    project_src: /opt/docker
    files:
      - docker-compose.yml

- name: Pause for 10 seconds to running all containers
  ansible.builtin.pause:
    seconds: 10
