- name: Create Wordpress data directory
  become: true
  ansible.builtin.file:
    path: /opt/docker/wp_data
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Create MySQL data directory
  become: true
  ansible.builtin.file:
    path: /opt/docker/mysql_data
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Create Prometheus data directory
  become: true
  ansible.builtin.file:
    path: /opt/docker/prometheus_data
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Put Prometheus config to volume
  become: true
  ansible.builtin.copy:
    src: ./files/prometheus.yml
    dest: /opt/docker/prometheus_data/prometheus.yml
    owner: root
    group: root
    mode: 0600

- name: Put docker-compose to volume
  become: true
  ansible.builtin.copy:
    src: ./files/docker-compose.yml
    dest: /opt/docker/docker-compose.yml
    owner: root
    group: root
    mode: 0600

- name: Deploy Docker Compose stack
  become: true
  community.docker.docker_compose:
    project_src: /opt/docker
    files:
      - docker-compose.yml
